	/*$("document").ready(function(){
		$("#2015").hide("fast");
		$("#2014").hide("fast");
		$("#2013").show("fast");
		$("#2012").hide("fast");
		$("#2011").hide("fast");
		$("#2010").hide("fast");
		$("#2009").hide("fast");
		$("#2008").hide("fast");
		$("#2007").hide("fast");
		$("#2006").hide("fast");
		$("#2005").hide("fast");
		$("#2004").hide("fast");
		$("#2003").hide("fast");
		$("#2002").hide("fast");
		$("#2001").hide("fast");
		$("#2000").hide("fast");
	});*/
	$(".Inicio").click(function(){
		$("#Inicio").show("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Mision").click(function(){
		$("#Mision").show("slow");
		$("#Inicio").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Vision").click(function(){
		$("#Vision").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Filosofia").click(function(){
		$("#Filosofia").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Contacto").click(function(){
		$("#Contacto").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Certificaciones").click(function(){
		$("#Certificaciones").show("slow");
		$("#Contacto").hide("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
	});
	$(".Clientes").click(function(){
		$("#Clientes").show("0");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Ambiente").click(function(){
		$("#Ambiente").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Fortalecimiento").click(function(){
		$("#Fortalecimiento").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Infraestructura").click(function(){
		$("#Infraestructura").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Practicas").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Practicas").click(function(){
		$("#Practicas").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Aviso").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Aviso").click(function(){
		$("#Aviso").show("slow");
		$("#Inicio").hide("slow");
		$("#Mision").hide("slow");
		$("#Vision").hide("slow");
		$("#Filosofia").hide("slow");
		$("#Contacto").hide("slow");
		$("#Clientes").hide("slow");
		$("#Ambiente").hide("slow");
		$("#Fortalecimiento").hide("slow");
		$("#Infraestructura").hide("slow");
		$("#Practicas").hide("slow");
		$("#Certificaciones").hide("slow");
	});
	$(".Start").click(function(){
		$("#Start").show("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Mission").click(function(){
		$("#Mission").show("slow");
		$("#Start").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Vission").click(function(){
		$("#Vission").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Philosophy").click(function(){
		$("#Philosophy").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Contact").click(function(){
		$("#Contact").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Customers").click(function(){
		$("#Customers").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Environment").click(function(){
		$("#Environment").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Organizational Strengthening").click(function(){
		$("#Organizational Strengthening").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Infrastructure").click(function(){
		$("#Infrastructure").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Infrastructure").click(function(){
		$("#Infrastructure").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Best practices").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Best practices").click(function(){
		$("#Best practices").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Privacy notice").hide("slow");
	});
	$(".Privacy notice").click(function(){
		$("#Privacy notice").show("slow");
		$("#Start").hide("slow");
		$("#Mission").hide("slow");
		$("#Vission").hide("slow");
		$("#Philosophy").hide("slow");
		$("#Contact").hide("slow");
		$("#Customers").hide("slow");
		$("#Environment").hide("slow");
		$("#Organizational Strengthening").hide("slow");
		$("#Infrastructure").hide("slow");
		$("#Best practices").hide("slow");
	});
